#!/bin/ksh

# -------------------------------------------------------------------------
# author Yahya.Mubaideen@ahli.com
# restart WAS Script for *ux
# -------------------------------------------------------------------------
RedC='\033[0;31m' # red Color
NoC='\033[0m' # no Color (default color)
YelC='\033[1;33m' # yellow Color
GreC='\033[0;32m' # green Color

serverName="server1"
serverPath=/IBM/WebSphere/AppServer/bin

# warning message before running the script
echo "${YelC}Restarting ${RedC}$serverName${YelC}, make sure TSM service is stopped before entering the password${NoC}"

# switch user and do some task then exit user, disposing stty message errors if any
su - wasadmin <<! >/dev/null 2>&1
# show please wait message redirecting it back to this terminal
echo "Correct password, please wait until END line" > /dev/tty

# change into directory that has programs to run
cd $serverPath

# stop the WAS server
./stopServer.sh $serverName -profileName AppSrv01 > /dev/tty

# after stopping wait for some seconds before starting
sleep 3
./startServer.sh $serverName -profileName AppSrv01 > /dev/tty

# end switch user and go back to previous user
!

# in case the user didn't input correct password 
echo "If this ended directly then maybe the password was wrong"

# finishing line
echo "${GreC}----------------END----------------${NoC}"
