#!/bin/ksh

# -------------------------------------------------------------------------
# author Yahya.Mubaideen@ahli.com
# release BCON tar script for *ux
# -------------------------------------------------------------------------
RedC='\033[0;31m' # red Color
NoC='\033[0m' # no Color (default color)
YelC='\033[1;33m' # yellow Color
GreC='\033[0;32m' # green Color

releasePath=/usr/Temenos/UD/F.BCON.DATA/RELEASE
scriptsPath=/usr/Temenos/TAFJ/bin

# check if user sent name of tar file
if [[ -z $1 ]];then
	echo "${RedC}No tar file name selected${NoC}"
	
# make sure there is a tar file named the same inside the release directory
elif [[ ! -f "$releasePath/$1.tar" ]];then
	echo "${RedC}No \"$1.tar\" file inside \"$releasePath\"${NoC}"
	
else
	# to avoid conflicts on login with username and password in the expect script
	print -n "${YelC}Are you sure no one else is using ${RedC}relBCON${YelC} at the same time? ${NoC}"; read answer
	if [[ $answer == Y || $answer == y || $answer == YES || $answer == Yes || $answer == yes ]];then
		# show please wait message
		echo "${YelC}Please wait until you can interact after BCON shows release results${NoC}"
		
		# change working directory
		cd $releasePath
		
		# extract the tar file
		tar -xvf "$1.tar"
		
		# show please wait message
		echo "${YelC}Don't forget to use ++ when you want to exit after BCON shows release results${NoC}"
		
		# call the expect script with name which automates t24 drill
		$scriptsPath/relBCON.exp $1
	fi
fi
# finishing line
echo "${GreC}----------------END----------------${NoC}"
